#### Words API

#### Get All Nouns
GET http://localhost:5000/api/nouns

#### Get All Verbs
GET http://localhost:5000/api/verbs

#### Get All Adjectives
GET http://localhost:5000/api/adjectives

#### Get All Adverbs
GET http://localhost:5000/api/adverbs

#### Get All Pronouns
GET http://localhost:5000/api/pronouns

#### Get All Prepositions
GET http://localhost:5000/api/prepositions
